### ISSUE TITLE
Undefined index: geocoder_service

### ISSUE THREAD

**Issue by ArchTaqi** [Happyr/LocationBundle#1]
I am using your bundle in my project, after setting it up, i got this exception 

```
ContextErrorException in HappyrLocationExtension.php line 30:
Notice: Undefined index: geocoder_service
```

**Comment by Nyholm** [comment]
Sorry for lack of documentation and configuration validation. I just made some refactoring on the bundle to not be dependent on any geocoder. 

You need to specify a service id for a class implementing the geocoder interface. https://github.com/Happyr/LocationBundle/blob/master/Geocoder/GeocoderInterface.php

```
happyr_location:
  geocoder_service: 'my.geocoder'
```

**Comment by Nyholm** [comment]
See this commit: 1da81b2a9c99fca6bdf983109c525ad9eae3a9ff

I've updated the Configuration.php and the docs.
